### ISSUE TITLE
adriconf is missing on Flathub.org?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/br.com.jeanhertel.adriconf#1]
The adriconf page is missing on the Flathub website and the Flatpak is also missing in GNOME Software. It looks like that there is some issue with the AppStream metadata.
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45246460-ca818a00-b2d7-11e8-8c03-984b7d9e9e33.png)

**Comment by nedrichards** [comment]
May be addressed by https://github.com/flathub/br.com.jeanhertel.adriconf/commit/5f49ca7e50f0f6a74633f7bb1bf88bcc4d1345ab

**Comment by LeandroStanger** [comment]
@nedrichards https://github.com/flathub/br.com.jeanhertel.adriconf/commit/5f49ca7e50f0f6a74633f7bb1bf88bcc4d1345ab did not solve the problem

**Comment by LeandroStanger** [comment]
@jlHertel https://github.com/flathub/br.com.jeanhertel.adriconf/commit/56e4fea67e54036a6cee561090b444f8af588c3e did not solve the problem

**Comment by jlHertel** [comment]
@nedrichards I think my last commit didn't rebuilt everything, so maybe rebuilding the package can solve the issue?

**Comment by jlHertel** [comment]
bot, build br.com.jeanhertel.adriconf

**Comment by LeandroStanger** [comment]
@jlHertel Did not work https://flathub.org/builds/#/builders/2/builds/4527

**Comment by velurimithun** [comment]
@nedrichards I verified both the xml and desktop files freedesktop software they are correct. Do you know why still this app isn't shown in flathub?
