### ISSUE TITLE
Crash on startup - Fedora 28 

### ISSUE THREAD

**Issue by velurimithun** [flathub/br.com.jeanhertel.adriconf#4]
Sep 17 11:28:59 dellirium systemd-coredump[8285]: Process 8280 (adriconf) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 2:
                                                  #0  0x00007f0df4f5ffba n/a (/usr/lib/x86_64-linux-gnu/libc-2.27.so)

Reported by Rob Clark (@robclark)

**Comment by jlHertel** [comment]
Hi @velurimithun 
Can you share your `$HOME/.drirc` and your `/etc/drirc` configuration files?

**Comment by jlHertel** [comment]
Fedore 28 defaults to Wayland, which is currently not supported.
The issue itself is that adriconf call glXGetScreenDriver which XWayland is not returning any data.

**Comment by velurimithun** [comment]
@jlHertel I think we can close this issue now

**Comment by jlHertel** [comment]
@velurimithun you are right, we can close this now.
